version: "3.8"

services:
  pg:
    image: postgres:14
    network_mode: host # port 5432
    environment:
      POSTGRES_PASSWORD: guest # user postgres

  pga:
    image: dpage/pgadmin4
    network_mode: host # port 80
    environment:
      PGADMIN_DEFAULT_EMAIL: g@g.gg
      PGADMIN_DEFAULT_PASSWORD: guest

  redis:
    image: redis/redis-stack
    network_mode: host # port 6379,8001

  mongo:
    image: mongo
    network_mode: host # port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest

  rmq:
    image: rabbitmq:3-management
    network_mode: host # port 5672,15672
    # user guest:guest

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    network_mode: host # port 9000,9001
    environment:
      MINIO_ROOT_USER: guest
      MINIO_ROOT_PASSWORD: guest123

  neo4j:
    image: neo4j
    network_mode: host # port 7474, 7687
    environment:
      - NEO4J_AUTH=none

  jaeger:
    image: jaegertracing/all-in-one
    network_mode: host # port 6831,14250,4317,16686

  prom:
    image: prom/prometheus
    command:
      - --enable-feature=otlp-write-receiver
    network_mode: host # port 9090
    volumes:
      - ./prom/prom.yml:/prometheus/prometheus.yml

  kafka:
    image: docker.io/bitnami/kafka:3.7
    network_mode: host # port 9092
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  keycloak:
    image: quay.io/keycloak/keycloak
    network_mode: host # port 8080
    environment:
      KEYCLOAK_ADMIN: guest
      KEYCLOAK_ADMIN_PASSWORD: guest
    command: start-dev
