version: '3.8'

x-kong-env: &kong-env
  KONG_PG_DATABASE: postgres
  KONG_PG_HOST: pg
  KONG_PG_USER: postgres
  KONG_PG_PASSWORD: guest

services:
  pg:
    image: postgres:14
    network_mode: host # port 5432
    environment:
      POSTGRES_PASSWORD: guest

  pga:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: g@g.gg
      PGADMIN_DEFAULT_PASSWORD: guest

  rd:
    image: redis/redis-stack
    network_mode: host # port 6379,8001

  mg:
    image: mongo
    network_mode: host # port 27017

  rmq:
    image: rabbitmq:3-management
    network_mode: host # port 5672,15672

  mio:
    image: minio/minio
    command: server /data --console-address :9001
    network_mode: host # port 9000,9001
    environment:
      MINIO_ROOT_USER: guest
      MINIO_ROOT_PASSWORD: guest123

  jg:
    image: jaegertracing/all-in-one
    network_mode: host # port 6831,14250,4317,16686

  kg-migrate:
    image: kong
    depends_on: [ pg ]
    command: kong migrations bootstrap
    environment:
      <<: *kong-env

  kg:
    image: kong
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8002:8002
      - 8444:8444
    environment:
      <<: *kong-env
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
