version: '3.8'

x-kong-env: &kong-env
  KONG_PG_DATABASE: postgres
  KONG_PG_HOST: pg
  KONG_PG_USER: postgres
  KONG_PG_PASSWORD: guest

services:
  pg:
    image: postgres:14
    network_mode: host # port 5432
    environment:
      POSTGRES_PASSWORD: guest

  pga:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: g@g.gg
      PGADMIN_DEFAULT_PASSWORD: guest

  redis:
    image: redis/redis-stack
    network_mode: host # port 6379,8001

  mongo:
    image: mongo
    network_mode: host # port 27017

  rmq:
    image: rabbitmq:3-management
    network_mode: host # port 5672,15672

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    network_mode: host # port 9000,9001
    environment:
      MINIO_ROOT_USER: guest
      MINIO_ROOT_PASSWORD: guest123

  jaeger:
    image: jaegertracing/all-in-one
    network_mode: host # port 6831,14250,4317,16686

  kafka:
    image: docker.io/bitnami/kafka:3.7
    network_mode: host # port 9092
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

  kg-migrate:
    image: kong
    depends_on: [ pg ]
    command: kong migrations bootstrap
    environment:
      <<: *kong-env

  kg:
    image: kong
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8002:8002
      - 8444:8444
    environment:
      <<: *kong-env
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
