version: "3.8"
services:
  es:
    image: elasticsearch:8.12.1
    network_mode: host # port 9200,9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1

  esvue:
    image: cars10/elasticvue
    network_mode: host # port 8080
