version: "3.8"
services:
  kong-db:
    image: postgres:14
    network_mode: host # port 5432
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass

  kong-migrate:
    image: kong/kong-gateway:3.8
    depends_on: [kong-db]
    command: kong migrations bootstrap
    network_mode: host
    environment:
      KONG_PG_HOST: localhost
      KONG_PG_PASSWORD: kongpass

  kong:
    image: kong/kong-gateway:3.8
    depends_on: 
      kong-migrate:
        condition: service_completed_successfully
    network_mode: host # port proxy:8000, admin:8001, gui:8002
    environment:
      KONG_PG_HOST: localhost
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_STATUS_ACCESS_LOG: /dev/stdout
      KONG_STATUS_ERROR_LOG: /dev/stderr
      KONG_TRACING_INSTRUMENTATIONS: all
      KONG_TRACING_SAMPLING_RATE: 1.0
